### ISSUE TITLE
Mod not appearing 

### ISSUE THREAD

**Issue by antony0330** [SuperNeon4ik/SelectiveGlowingFabric#1]
I installed the mod and the right version of fabric, but it doesnt seem to appear in the game mod list, not the effects of the mod are active. Am I missing something?

**Comment by SuperNeon4ik** [comment]
Hello! 
I suppose you tried putting the mod in your client. If so, that is unsupported.
This mod can only be installed on the server and doesn't need to be installed on the client.

**Comment by SuperNeon4ik** [comment]
Hi! Just checking in. Did the answer above help you? If yes, please tell me so I can close the issue. If otherwise, could you give me more information on the issue and how to reproduce it. Thank you!
